spring:
  application:
    name: chatApp

  #MondoDB
  data:
    mongodb:
      uri: ${MONGODB_HOST}
      database: chatAppDB

  #FileTransfer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#Looging
logging:
  level:
    root: INFO

#Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_CLOUD_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}